Cleanup typos and grammar in error messages.

diff --git a/send/bbmri_collections b/send/bbmri_collections
--- a/send/bbmri_collections
+++ b/send/bbmri_collections
@@ -33,9 +33,9 @@ cat "$USER_FILE" | timeout -k $TIMEOUT_KILL $TIMEOUT $USER_TRANSPORT_COMMAND
 ERR_CODE=$?
 #Error code 124 means - timeouted
 if [ $ERR_CODE -e 124 ]; then
-	echo "Communication with the peer was timeouted with return code: $ERR_CODE (Warning: this error can mask original error 124 from peer!)" >&2
+	echo "Communication with the peer has timed out with return code: $ERR_CODE (Warning: this error can mask original error 124 from peer!)" >&2
 else
-	echo "Communcation with the peer ends with return code: $ERR_CODE" >&2
+	echo "Communication with the peer ends with return code: $ERR_CODE" >&2
 fi
 
 # HTTP Request with timeout for GROUPS
@@ -44,9 +44,9 @@ cat "$GROUP_FILE" | timeout -k $TIMEOUT_KILL $TIMEOUT $GROUP_TRANSPORT_COMMAND
 ERR_CODE=$?
 #Error code 124 means - timeouted
 if [ $ERR_CODE -e 124 ]; then
-  echo "Communication with the peer was timeouted with return code: $ERR_CODE" >&2
+  echo "Communication with the peer has timed out with return code: $ERR_CODE" >&2
 else
-	echo "Communcation with the peer ends with return code: $ERR_CODE (Warning: this error can mask original error 124 from peer!)" >&2
+	echo "Communication with the peer ends with return code: $ERR_CODE (Warning: this error can mask original error 124 from peer!)" >&2
 fi
 
 exit $ERR_CODE
