refactor(drupal_elixir): use only warning when duplicate users are found * with duplicate users the slave script needs to end with an ok return code in order to prevent rerun of the propagation with the same data

diff --git a/slave/base/bin/perun b/slave/base/bin/perun
--- a/slave/base/bin/perun
+++ b/slave/base/bin/perun
@@ -131,6 +131,17 @@ function log_msg_without_exit {
 	fi
 }
 
+### Log message to stderr and exit with 0 return code
+function log_warn_to_err_exit {
+	TEXT="$1"
+	TIME=`date "+%H:%M:%S"`
+
+	MSG="Info: ${TEXT}"
+	echo "${TIME} ${MSG}" >&2
+	logger -t "${NAME}" -p daemon.error "${SERVICE}: ${MSG}" &>/dev/null
+	exit 0
+}
+
 ### Log debug only if variable DEBUG exists and is the length of this variable is nonzero
 function log_debug {
 	MSG="$1"
